//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public Nullable<System.DateTime> DataNascimento { get; set; }
        public Nullable<bool> tipoBancario { get; set; }
        public Nullable<int> agencia { get; set; }
        public Nullable<int> conta { get; set; }
        public string tipoConta { get; set; }
        public string chavePix { get; set; }
    }
}
